### ISSUE TITLE
IOS Implementation

### ISSUE THREAD

**Issue by lejard-h** [dart-flitter/flutter_webview_plugin#1]

**Comment by sethladd** [comment]
This comes up a lot when we talk to developers. Would love to see this!

**Comment by lejard-h** [comment]
We would love too, unfortunately, we cannot do the IOS part, so if anybody want to do it, feel free to submit a pull request ;)

**Comment by lejard-h** [comment]
fixed here https://github.com/dart-flitter/flutter_webview_plugin/pull/3
