### ISSUE TITLE
File Upload not working in flutter webview

### ISSUE THREAD

**Issue by rubixcoder** [dart-flitter/flutter_webview_plugin#100]
Hi,

I am raising the existing issue #99. Please provide solution to this asap or at least let us know the ETA.

@lejard-h @sethladd @xqwzts @ypelud @pedia @mclark4386 @jparound30 @howardt12345 @mclark4386 @Mohammed90 @long1eu @ciceroduarte @totalorder @tenhobi

**Comment by Kleak** [comment]
Please use existing issues if it cover the same bug, instead you can add a :+1: on the existing one :)

**Comment by rubixcoder** [comment]
Okay, but please at least acknowledge that issue and provide the ETA.

Thanks!!
