### ISSUE TITLE
Load web view in a defined reactangle

### ISSUE THREAD

**Issue by gedw99** [dart-flitter/flutter_webview_plugin#106]
This would be cool because then you can then put flutter navy bars and other things outside the web view and use the web view just for forms.

I am not sure but I think the other web view for flutter allows this.

**Comment by peter9teufel** [comment]
As far as I know from my current project, you can use the launch(url, rect: rect) method of the webview plugin to specify a rectangle for the webview on launching an URL, the second way would be to use the resize(rect) method of the webview plugin.

**Comment by gedw99** [comment]
Ook wil try it - thanks
