### ISSUE TITLE
How to load the local html

### ISSUE THREAD

**Issue by Sky24n** [dart-flitter/flutter_webview_plugin#111]

**Comment by gedw99** [comment]
Yep.

It would lower slot of confusion if you make an example using dart code
that loads the webview from a local webserver and a remote webserver.
Add websockets to it as icing on the cake.

That will make it way easier for people to use this..

**Comment by zoechi** [comment]
@gedw99 isn't that what the medium link in the 2nd comment in #23 does? (at least the local webserver stuff)

**Comment by Sky24n** [comment]
@zoechi  very thankful，I used your method to load the local web pages successfully

**Comment by zoechi** [comment]
@Sky24n would be great if you could close this duplicate issue.
