### ISSUE TITLE
FullScreen Webview without Appbar draws behind the status bar. 

### ISSUE THREAD

**Issue by LucianoSP** [dart-flitter/flutter_webview_plugin#118]
I´m using the following code to launch the webview:
`return new MaterialApp(
        debugShowCheckedModeBanner: false,
        home: WebviewScaffold(
          withZoom: true,
          withJavascript: true,
          withLocalStorage: true,
          primary: true,
          clearCache: false,
          url: url,
          
        ));
  }`

The problem is the website draws under the status bar. I can´t find a way to hide the status bar (not ideal) or insert some padding to the webview. How can this be accomplished, please?

**Comment by LucianoSP** [comment]
![celular](https://user-images.githubusercontent.com/10941537/42237413-109fae82-7ed4-11e8-84d2-cec7950d1417.jpg)

**Comment by LucianoSP** [comment]
I found that SystemChrome.setEnabledSystemUIOverlays([]) hides the status bar, that should do it.

**Comment by sameerbakre** [comment]
Is there any workaround for keeping status bar?

**Comment by 5hanth** [comment]
@sameerbakre you need to use SafeArea() plugin.

**Comment by August0Cesar** [comment]
> @sameerbakre you need to use SafeArea() plugin.

This works great for me.
https://www.youtube.com/watch?v=lkF0TQJO0bA
