### ISSUE TITLE
Notify when URL changes

### ISSUE THREAD

**Issue by gurmukhp** [dart-flitter/flutter_webview_plugin#13]
Would it be possible to add a feature to know when the URL of the browser has changed?

Currently using Oauth2, if a http server is the redirect, some apps show a warning to the user that the credentials are being sent to an insecure server.

If https is used, then iOS throws an error loading the redirect url.

**Comment by lejard-h** [comment]
it should be easy to do on Android, but no idea on iOS, @toufikzitouni an idea ?

**Comment by toufikzitouni** [comment]
@lejard-h not on the top of my head. Do you have an Android implementation? I can work off of it and mimic the logic on iOS

**Comment by lejard-h** [comment]
I will implement it this week end, but basically I plan to use builtin methods form the Android Webview and send the url to a Dart Stream.

**Comment by toufikzitouni** [comment]
@lejard-h sounds good! I can work off of your implementation once done for iOS

**Comment by lejard-h** [comment]
I implemented it

https://github.com/dart-flitter/flutter_webview_plugin/blob/master/lib/flutter_webview_plugin.dart#L36
https://github.com/dart-flitter/flutter_webview_plugin/blob/master/android/src/main/java/com/flutter_webview_plugin/WebviewActivity.java#L103

Let me know if you need explanation or if you have remarks

**Comment by marwan-at-work** [comment]
any luck with the ios implementation?

**Comment by pedia** [comment]
#18  This coming in pull request.

**Comment by marwan-at-work** [comment]
@pedia that’s great! Hope it gets merged soon

**Comment by lejard-h** [comment]
will be fix in the next release, after https://github.com/dart-flitter/flutter_webview_plugin/issues/21 get fixed @pedia
