### ISSUE TITLE
Flutter Webviewscaffold issue with device back button

### ISSUE THREAD

**Issue by shuzuka12** [dart-flitter/flutter_webview_plugin#131]
I created tabs using HTML and later i called HTML content in Webviewscaffold in flutter.
When I click on device back button it need to navigate previous screen but it is displaying empty screen with an Appbar.  Is their any device back button handler in Webviewscaffold? or suggest me any other solution to overcome this issue.

**Comment by While1true** [comment]
first: load a url;
second: pressed a loading-more button on html
third: pressed device's back button;
it is displaying a circle-progressbar in middle of the screen with an Appbar.
rather than goback or finish this page

When I click on device back button it need to navigate previous screen but it is displaying circle-progressbar screen with an Appbar.

**Comment by Code-PLeX** [comment]
a hack is to set a callback method to exit(0) onDestroy

    _webviewPlugin.onDestroy.listen((_) => exit(0));

it fixed the issue for me

**Comment by samzzz** [comment]
Where do you put this line
`_webviewPlugin.onDestroy.listen((_) => exit(0));`
in the example ?
https://github.com/dart-flitter/flutter_webview_plugin/blob/master/example/lib/main.dart

**Comment by Code-PLeX** [comment]
under initState

**Comment by shuzuka12** [comment]
Hey Thanks. I used onDestroy() in initState() working fine.

**Comment by Hmaal** [comment]
> Is it posible to do this when using the widget version?
> 
> > ```
> >         WebviewScaffold(
> >           url: selectedUrl,
> >           appBar: new AppBar(
> >             title: const Text('Widget webview'),
> >           ),
> >           withZoom: true,
> >           withLocalStorage: true,
> >         )
> > ```

I too am curious about this. If not, is there an alternative way to use the plugin as a widget without explicitly using the widget version?
