### ISSUE TITLE
WebviewScaffold crash on iOS 11.4 device with release build

### ISSUE THREAD

**Issue by va-andrew** [dart-flitter/flutter_webview_plugin#134]
This app opens properly the first time after running with `--release`. After closing the app and opening again, it usually (but not always) crashes immediately.

Minimal example:
```
import 'package:flutter/material.dart';
import 'package:flutter_webview_plugin/flutter_webview_plugin.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Flutter Demo',
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => new _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return WebviewScaffold(
      url: 'https://www.google.com',
      appBar: AppBar(
        leading: IconButton(
          icon: Icon(Icons.account_balance),
          onPressed: () {},
        ),
        title: Text('WebView test')
      ),
    );
  }
}
```

Device: iPhone 6, iOS 11.4.1
Plugin version: 0.1.6
Flutter doctor:
```
[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.6 17G65, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] VS Code (version 1.25.1)
[✓] Connected devices (1 available)
```

**Comment by va-andrew** [comment]
Enforcing a non-negative webview height seems to solve this -- #135

**Comment by jayrmotta** [comment]
Hey, thanks for the contribution, I'm looking forward it to be accepted. Don't you think adding plus one to the minor version of the package is a good idea given this improvement?

**Comment by jayrmotta** [comment]
I've been trying exactly the same thing on the example project and it's not working on iOS, works fine on Android.

Versions of iOS tested:
- 10.3.1
- 11.3
- 11.4

Versions of Android tested:
- API 28 (Oreo)

Basically my code imports both the web view plugin and the jaguar web server, creates a web server to serve an asset that has been declared on my `pubspec.yaml`, added dependencies to `pubspec.yaml` (tried the original plugin and @va-andrew fork), I then replaced the default event listener on the button for the flutter starter. Pretty straightforward.
