### ISSUE TITLE
Allow mailto and tel URL schemes

### ISSUE THREAD

**Issue by surbhitydy** [dart-flitter/flutter_webview_plugin#137]
I have created an app using flutter and I am using flutter web view to show few of my contents. And in my web view I have two buttons to perform **mailto** and **tel**, but these are not working. On iOS when I am clicking on these buttons there is nothing happening and on Android it's even worse because it shows me an error **ERR_UNKNOWN_URL_SCHEME**.

**P.S:** I have already allowed for the permissions required for this.

Please let me know that when you can fix this issue.

**Comment by jayrmotta** [comment]
Same issue here, trying to link back to the app using custom URL schemes but getting ERR_UNKNOWN_URL_SCHEME.

**Comment by surbhitydy** [comment]
@lejard-h @pedia 
Anyone please look into this issue. It's kind of urgent for my app.

Thanks!

**Comment by lejard-h** [comment]
duplicate https://github.com/dart-flitter/flutter_webview_plugin/issues/43

**Comment by tony123S** [comment]
How to use url launcher in WebView?
