### ISSUE TITLE
Webview.postURL equivalent

### ISSUE THREAD

**Issue by shashkiranr** [dart-flitter/flutter_webview_plugin#146]
Hi,

Is there a way to post params to a webpage using the webview like standard dart http plugin http.post(url, body: body).

**Comment by lejard-h** [comment]
you cannot send http POST on a webpage.

What do you want to achieve ?

**Comment by shashkiranr** [comment]
Hi lejard-h,

I want to post parameters(name, number,..) to a payment gateway page which in turn redirects to another page to complete the payment.

**Comment by lejard-h** [comment]
A workaround is to have a javascript function in the page you load that do it for you.

Then call the function from the dart side using the plugin.

`webviewPlugin.evalJavascript('postFunction("$name", $number)');`

**Comment by kaijing1115** [comment]
webviewPlugin.evalJavascript('postFunction("$name", $number)'); cannot work in ios.
The webview plugin I use is flutter_webview_plugin. Can give me some advice. 
Thank you

**Comment by HaoCherHong** [comment]
use webViewController.evalJavascript() to do the following:
https://snipplr.com/view/66619/post-form-with-javascript-nonajax/

**Comment by fauzi2107** [comment]
hi @kaijing1115 did you found the solution already?

**Comment by kaijing1115** [comment]
> hi @kaijing1115 did you found the solution already?

@fauzi2107 
I can call successfully if put it under onStateChanged instead of onUrlChanged. Can try code below

```
_onStateChanged = flutterWebviewPlugin.onStateChanged.listen((state) async{
    
        if(state.type == WebViewState.finishLoad){
            flutterWebviewPlugin.evalJavascript('postFunction("$name", $number)');
        }

      });
_onUrlChanged = flutterWebviewPlugin.onUrlChanged.listen((String url) async{}

```
