### ISSUE TITLE
Flutter timer issue when screen is locked

### ISSUE THREAD

**Issue by shuzuka12** [dart-flitter/flutter_webview_plugin#148]
I am working on session time out. when app is in background state timer is working fine  and after time expires it will redirect to home screen. but when i lock the screen timer is taking more time beyond the actual time. it giving time difference when screen is locked and unlocked.

For time count used Timer.periodic() constructor.

Can anyone help me on this issue.

**Comment by lejard-h** [comment]
probably due to flutter engine, I guess the process is stoped when the phone is locked.

But you can try to use a timestamp and get the time elapsed when the app is resume using WidgetsBindingObserver

https://docs.flutter.io/flutter/widgets/WidgetsBindingObserver-class.html

**Comment by lejard-h** [comment]
I will close the issue since it is not related to the webview plugin
