### ISSUE TITLE
0.2.1 bug

### ISSUE THREAD

**Issue by farukzahra** [dart-flitter/flutter_webview_plugin#150]
flutter_webview_plugin-0.2.1\android\src\main\java\com\flutter_webview_plugin\WebviewManager.java:100: error: cannot find symbol
        observableWebView = (ObservableWebView) webView;
        ^
  symbol:   variable observableWebView
  location: class WebviewManager

**Comment by dannysood** [comment]
Facing the same issue. @farukzahra how did you get around it or did you downgrade to 2.0?

**Comment by farukzahra** [comment]
downgrade to 2.0

**Comment by subanmiao** [comment]
Facing the same issue too. Any idea on how to resolve this problem? downgrade to 0.1.6?

**Comment by dannysood** [comment]
@subanmiao I downgraded to 2.0 and works fine for me.

**Comment by l-k22** [comment]
Tried1 0.2.0 but still have the same error. Downgrading to 0.1.6 works
