### ISSUE TITLE
Update Dart SDK version is 2.1.0

### ISSUE THREAD

**Issue by NguyenSen** [dart-flitter/flutter_webview_plugin#170]
The current Dart SDK version is 2.1.0-dev.1.0.flutter-69fce633b7.

Because trendmicro depends on flutter_webview_plugin >=0.0.2 <0.2.0 which requires SDK version <2.0.0, version solving failed.
pub upgrade failed (1)
'L' is not recognized as an internal or external command,
operable program or batch file.

**Comment by souther** [comment]
Same problem here D: hope they update they plugin soon :D

**Comment by NguyenSen** [comment]
edit confng version is 0.2.1+2
