### ISSUE TITLE
Navigation drawer

### ISSUE THREAD

**Issue by gedw99** [dart-flitter/flutter_webview_plugin#24]
Is it possible to add a navigation drawer widget ? The readme suggests that this is not possible but want to get an opinion on this.

The reason being that the navigation drawer is much smoother

**Comment by lejard-h** [comment]
Not possible for now, the webview is not a flutter widget. If you want a drawer you will have to use natives for Android and iOS.

But maybe in the next version (blocked by https://github.com/dart-flitter/flutter_webview_plugin/issues/21), you will be able to hack something, it will be possible to create webview of a specific size and place it where you want it on top of a flutter view so you can still interact with it.

**Comment by gedw99** [comment]
ok... good to know...
Will wait

**Comment by lejard-h** [comment]
I am closing this issue since, this the webview is not a Flutter widget and cannot add to the widget tree, it is not possible redraw flutter widget on top of the native view.

tracked issue on flutter repo => https://github.com/flutter/flutter/issues/13790
