### ISSUE TITLE
Remove the appbar???

### ISSUE THREAD

**Issue by lunvjp** [dart-flitter/flutter_webview_plugin#27]
When I launch webview in flutter, I don't need the appbar (back button and the title). How can I remove it?

![image](https://user-images.githubusercontent.com/23715737/34870521-e518645a-f7bc-11e7-9b06-c2bd02e49c76.png)
Seem like this is the arguments for function "launch", but I can't use it as well..
Thanks you guys.

**Comment by lejard-h** [comment]
how did you launch the webview ? `launch` function should `fullscreen: true` by default.

**Comment by lunvjp** [comment]
That's right.
![image](https://user-images.githubusercontent.com/23715737/34870632-4cc01850-f7bd-11e7-8d0c-fea04a538c6b.png)

**Comment by lunvjp** [comment]
That's right
![image](https://user-images.githubusercontent.com/23715737/34870660-5edb77dc-f7bd-11e7-9782-4e0d64916f43.png)

**Comment by lunvjp** [comment]
Can I delete the appbar?

**Comment by lejard-h** [comment]
is it working ? are you importing the dependencies via `pub` or `github` ?

**Comment by lejard-h** [comment]
on iOS, it should be fullscreen, on Android you have to personalize the activity that you are using to host the webview.
`<activity android:name="com.flutter_webview_plugin.WebviewActivity" android:parentActivityName=".MainActivity"/>`

**Comment by lunvjp** [comment]
It's working well, but I don't need the appbar. So Is there any way to remove the appbar ?

**Comment by lunvjp** [comment]
Is there any versions to help me with it?

**Comment by lunvjp** [comment]
![image](https://user-images.githubusercontent.com/23715737/34900558-950088ae-f833-11e7-83fb-617621fd49cd.png)
I mean this appbar. Can I hidden this one? I really need your help

**Comment by lejard-h** [comment]
This app bar is comming from your Android theme, you can hide it by changing the theme of the activity you are using for the webview inside the app manifest.

**Comment by lunvjp** [comment]
Thank you so much.. I changed to this.
<activity android:name="com.flutter_webview_plugin.WebviewActivity" android:parentActivityName=".MainActivity"
                  android:theme="@android:style/Theme.NoTitleBar"/>
