### ISSUE TITLE
Check the url after that url of webview be changed

### ISSUE THREAD

**Issue by lunvjp** [dart-flitter/flutter_webview_plugin#28]
I mean when I launch url: 'https://flutter.io', it will have a callback to check url. Then I click to a link in this webview like: 'https://flutter.io/setup', it will have a callback to check url.
Something like: jQuery("#url_adress").change(function(url){ // Check url });
Is there any solutions to help me with it?
Thanks guys so much.

**Comment by Kleak** [comment]
Maybe [this](https://github.com/dart-flitter/flutter_webview_plugin/blob/master/lib/flutter_webview_plugin.dart#L56) Stream do what you need ? 
If it's not the case can you be little more explicit about what is the use case ?

**Comment by lunvjp** [comment]
Thanks. I found my solution with "onUrlChanged". Nice!
