### ISSUE TITLE
I hope to increase the way to get the title of the web page

### ISSUE THREAD

**Issue by dengsgo** [dart-flitter/flutter_webview_plugin#30]
I hope to increase the way to get the title of the web page. Under normal circumstances, the appbar title should display the title of the page

**Comment by lejard-h** [comment]
with the last version (`0.1.0`) you can use `WebviewScaffold`, `onUrlChanged` and `evalJavascript`.

```dart
flutterWebviewPlugin.onUrlChanged.listen((url) async {
   webviewTitle = await flutterWebviewPlugin.evalJavascript("window.document.title");
   setState(() => {});
});

...

new WebviewScaffold(
              url: "https://www.google.com",
              appBar: new AppBar(
                title: new Text(webviewTitle),
              ),
            );
```

let me know if you get any problems, either way I will close the issue

**Comment by dengsgo** [comment]
Cool, thank you for your answer.

**Comment by l-k22** [comment]
I'm a little confused by this, I can get the webviewscaffold to work with a bottomnavigationbar when it is returned directly in my build method. However, I now have a listview of flatbuttons which act as my ebook's contents page. When the user clicks a list item I'd like it to open the webview with a bottomnavigationbar so they can navigate the book and also return to the listview.
