### ISSUE TITLE
Get the source

### ISSUE THREAD

**Issue by gedw99** [dart-flitter/flutter_webview_plugin#31]
I want to print the HTML as a PDF.
I am using the HTML print plugin for flutter.

There is no method to ask for the HTML from the webview it seems ?

**Comment by lejard-h** [comment]
did you try [evalJavascript](https://www.dartdocs.org/documentation/flutter_webview_plugin/0.1.0%2B1/flutter_webview_plugin/FlutterWebviewPlugin/evalJavascript.html) with "document.documentElement.innerHTML" ? you could also try to call `print()` in the webView, but never, I don't know what could happen.

**Comment by gedw99** [comment]
thanks. Ok going to try this out. Who knows.

For desktop webviews BTW print does not work... Annoying.. SO i have to feed the html to a htmlToPdf converter out of prcoess.

Anyway will try and let you know..

**Comment by gedw99** [comment]
your suggestion works. thanks @lejard-h

**Comment by lejard-h** [comment]
:+1:
