### ISSUE TITLE
MissingPluginException(No implementation found for method close on channel flutter_webview_plugin)

### ISSUE THREAD

**Issue by arnoldparge** [dart-flitter/flutter_webview_plugin#33]
I am trying to have WebView in Flutter using WebviewScaffold widget.

I have installed flutter_webview_plugin: "^0.1.0+1"

but I am getting ERROR:
MissingPluginException(No implementation found for method close on channel flutter_webview_plugin)
.
.
.
MissingPluginException(No implementation found for method launch on channel flutter_webview_plugin)
.
.
.

Below is how my page looks like:

```
import 'package:flutter/material.dart';
import 'package:flutter_webview_plugin/flutter_webview_plugin.dart';


class BulkProductUpdatePageRoute extends MaterialPageRoute {
  BulkProductUpdatePageRoute():
      super(builder: (BuildContext context) => new BulkProductUpdatePage());
}

class BulkProductUpdatePage extends StatefulWidget {
  @override
  _BulkProductUpdatePageState createState() => new _BulkProductUpdatePageState();
}

class _BulkProductUpdatePageState extends State<BulkProductUpdatePage> {

  @override
  Widget build(BuildContext context) {
    return new WebviewScaffold(
      appBar: new AppBar(
        leading: new RetailAppBarLeading(),
        title: new Text('Bulk Product Update'),
        bottom: appBarBottom(
          child: new Container(
            child: new TextField(
              decoration: new InputDecoration(
                  icon: new Icon(
                    Icons.search,
                    color: Colors.grey,
                  ),
                  hideDivider: true,
                  hintText: 'Search Products'
              ),
            ),
            padding: new EdgeInsets.only(
                bottom: 5.0
            ),
          ),
        ),
      ),
      url: 'https://pub.dartlang.org/packages/flutter_webview_plugin#-installing-tab-',
    );
  }
}

```

**Comment by lejard-h** [comment]
It's like you did get the updated dart code but not the iOS/Android one.
Can you try to remove `pubspec.lock` and `.pub` then redo a `flutter packages get` ?

**Comment by zoechi** [comment]
Deleting `flutter packages upgrade` should do the same as deleting `pubspec.lock` and running `flutter packages get`

**Comment by Salvatore-Giordano** [comment]
Did you solve in some way? I'm having the same error

**Comment by IanDarwin** [comment]
"Me too." As Hadrien suggested I removed pubspec.lock. As zoechi suggested I did flutter packages upgrade, then a full reload. Alas, I'm still getting the same error messages as the OP and just a spinning activity indicator in an otherwise-blank web page. This is on iOS; will try on Android when I get home. Installed by the book as per the "Installing" tab on the github project page. TIA if anyone can help!

**Comment by IanDarwin** [comment]
I was having the same problem but it went away on its own, probably something wasn't clean. Restarted my Mac on Monday morning, rebuild and reloaded everything and my Help route via WebView is working fine on both platforms.

**Comment by zoechi** [comment]
`flutter clean` might help. I have this occasionally recently that some changes don't take effect.

**Comment by IanDarwin** [comment]
Yes, that's what I meant by "rebuilt and reloaded everything", `flutter clean run` forces it to rebuild everything in sight.

**Comment by tiagosito** [comment]
@lejard-h  and others devs...
I have already performed the procedures of [Restart mac, flutter clean] and still it continues with error below

ERROR:
[VERBOSE-2: dart_error.cc (16)] Unhandled exception:
MissingPluginException (No implementation found for method launch on channel flutter_webview_plugin)

0 MethodChannel.invokeMethod (package: flutter / src / services / platform_channel.dart: 278: 7)
<asynchronous suspension>

1 FlutterWebviewPlugin.launch (package: blablabla / webview / base.dart: 103: 20)
<asynchronous suspension>

2 _WebviewScaffoldState.build (package:blablabla/ webview_scaffold.dart: 62:24)

**Comment by Kumuda123** [comment]
Hey I am having the same problem. Did you find a solution ?

**Comment by manondidi** [comment]
> Hey I am having the same problem. Did you find a solution ?

i have same issue,did you fix ?

**Comment by Kumuda123** [comment]
No i did not fix the issue !

**Comment by manondidi** [comment]
> No i did not fix the issue !

it work fine in single flutter project but not in a exiting project add into flutter
what about you?

if cant fix ,what should we do? give up flutter in this function,use native develop it?

**Comment by responilla07** [comment]
@arnoldparge @Kumuda123 

I just fixed the issue on my side right now. I stop first the app then;

flutter clean
flutter clean cached --all
then ctrl + s in pubspec.yaml

in my pubspec i have this,  'flutter_webview_plugin:' and my flutter version is 1.17.5

**Comment by ankit-tyagi123** [comment]
I am also having same issue. Stuck from last 2 days. None of above solution worked for me.
