### ISSUE TITLE
Zoom support

### ISSUE THREAD

**Issue by Gustik** [dart-flitter/flutter_webview_plugin#34]
I want zoom content in webview with gestures. Is it possible?

**Comment by Gustik** [comment]
Yes, I do not have zoom. I use Android.
My widget where I use the webview
```
class DocumentPage extends StatelessWidget {
  final Document _document;

  DocumentPage(this._document);

  @override
  Widget build(BuildContext context) {
    return new WebviewScaffold(
      url: "http://example.org/pdf.php?doc=docs/project/${_document.file}",
      appBar: new AppBar(
        title: new Text(_document.name),
      ),
      withJavascript: true,
    );
  }
```

}

**Comment by agreensh** [comment]
Although pinch and zoom are built-in to WebView (Android) and UIWebView (iOS), they need to be "switched-on".

In Android, the plugin needs to call the following :
**_webView.WebSettings.setBuiltInZoomControls(true);_** to allow pinch/zoom.

In iOS, the plugin needs to call the following:
**_self.webview.scalesPageToFit = YES;_** to allow pinch/zoom.

**Comment by lejard-h** [comment]
Tested on Android, it does not seem to work,

But I have not tested on iOS

**Comment by agreensh** [comment]
I have tested on Android and iOS. It does work.

Remember, you also have to take into account the web page - the meta data can prevent pinch/zoom (eg in your example, the page (https://github.com/dart-flitter/flutter_webview_plugin) does that by setting `<meta name='viewport' content='width=device-width'>`, so that page will NOT pinch/zoom). Try on another page that is 'reactive' eg 'https://flutter.io'

If that doesn't work, then I think you've put the code in the wrong place.

On Android

```
WebviewManager(Activityactivity) {
    this.webView = new WebView(activity);
    this.webView.getSettings().setBuiltInZoomControls(true);
    this.webView.getSettings().setSupportZoom(true);
    WebViewClient webViewClient = new BrowserClient();
    webView.setWebViewClient(webViewClient);
}

```

**Comment by Gustik** [comment]
Tried to open a 'https://flutter.io', all the same the zooming does not work.
But the patch works:
```
this.webView.getSettings().setBuiltInZoomControls(true);
this.webView.getSettings().setSupportZoom(true);
```
Thanks!

**Comment by lejard-h** [comment]
fixed in `0.1.3`

**Comment by mexme** [comment]
I am aware that we now have WKWebView. However I for one would love to disable zooming altogether (pinch, doubletap). It seems that 'withZoom: false' doesn't have any effect (fullscreen WebView with flutter navigation)?
Any hints maybe?

**Comment by AleksandarFaraj** [comment]
Can we split up ZoomControls and SupportZoom into two variables?
ZoomControls could be named AndroidZoomControl: boolean

**Comment by TheSunilVarma** [comment]
> Tried to open a 'https://flutter.io', all the same the zooming does not work.
> But the patch works:
> 
> ```
> this.webView.getSettings().setBuiltInZoomControls(true);
> this.webView.getSettings().setSupportZoom(true);
> ```
> 
> Can make it optional? e.g. 'withZoom: true'
> Thanks!

Hello @Gustik .... Where do we need to call this patch (Location Please ?)

**Comment by kakyoism** [comment]
Need a step-by-step for this. I'm not sure how to add the native code in Kotlin, Swift, at the exact place.
