### ISSUE TITLE
ActivityNotFoundException

### ISSUE THREAD

**Issue by Iccr** [dart-flitter/flutter_webview_plugin#39]
I am having problem with starting web_view in android. I used flutter_facebook_connect which opens webview for facebook authentication. It works on iOS,  however Android build seems to have problem. here is the build log. 

Launching lib/main.dart on c5674b2c in debug mode...
Initializing gradle...
Resolving dependencies...
Running 'gradlew assembleDebug'...
Built build/app/outputs/apk/app-debug.apk (27.2MB).
Installing build/app/outputs/apk/app.apk...
I/FlutterActivityDelegate(13525): onResume setting current activity to this
Syncing files to device c5674b2c...
D/skia    (13525): [SkFontMgr Android Parser] '/system/etc/fonts.xml' could not be opened
D/skia    (13525): [SkFontMgr Android Parser] '/vendor/etc/fallback_fonts.xml' could not be opened
E/MethodChannel#flutter_webview_plugin(13525): Failed to handle method call
E/MethodChannel#flutter_webview_plugin(13525): android.content.ActivityNotFoundException: Unable to find explicit activity class {com.veda.roomFinder/com.flutter_webview_plugin.WebviewActivity}; have you declared this activity in your AndroidManifest.xml?
E/MethodChannel#flutter_webview_plugin(13525): 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1556)
E/MethodChannel#flutter_webview_plugin(13525): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1431)
E/MethodChannel#flutter_webview_plugin(13525): 	at android.app.Activity.startActivityForResult(Activity.java:3429)
E/MethodChannel#flutter_webview_plugin(13525): 	at android.app.Activity.startActivityForResult(Activity.java:3390)
E/MethodChannel#flutter_webview_plugin(13525): 	at com.flutter_webview_plugin.FlutterWebviewPlugin.openUrl(FlutterWebviewPlugin.java:55)
E/MethodChannel#flutter_webview_plugin(13525): 	at com.flutter_webview_plugin.FlutterWebviewPlugin.onMethodCall(FlutterWebviewPlugin.java:36)
E/MethodChannel#flutter_webview_plugin(13525): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:191)
E/MethodChannel#flutter_webview_plugin(13525): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:128)
E/MethodChannel#flutter_webview_plugin(13525): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter_webview_plugin(13525): 	at android.os.MessageQueue.next(MessageQueue.java:125)
E/MethodChannel#flutter_webview_plugin(13525): 	at android.os.Looper.loop(Looper.java:124)
E/MethodChannel#flutter_webview_plugin(13525): 	at android.app.ActivityThread.main(ActivityThread.java:4960)
E/MethodChannel#flutter_webview_plugin(13525): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/MethodChannel#flutter_webview_plugin(13525): 	at java.lang.reflect.Method.invoke(Method.java:511)
E/MethodChannel#flutter_webview_plugin(13525): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1038)
E/MethodChannel#flutter_webview_plugin(13525): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
E/MethodChannel#flutter_webview_plugin(13525): 	at dalvik.system.NativeStart.main(Native Method)
I/FlutterActivityDelegate(13525): onResume setting current activity to this
W/DynamiteModule(13525): Local module descriptor class for com.google.firebase.auth not found.
W/IInputConnectionWrapper(13525): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper(13525): setComposingText on inactive InputConnection

**Comment by biklas7** [comment]
Same error here :
`Unable to find explicit activity class {com.myapp.myapp/com.flutter_webview_plugin.WebviewActivity}`

**Comment by lejard-h** [comment]
Sorry I have just updated the README, flutter_facebook_connect is not updated anymore. it is using an old version of the webview that need the AndroidActivity. You should use [flutter_facebook_login](https://github.com/roughike/flutter_facebook_login) instead
