### ISSUE TITLE
<Summarize your issues here>

### ISSUE THREAD

**Issue by isoos** [dart-flitter/flutter_webview_plugin#44]
_From @GokulDharumar on March 12, 2018 19:28_

URL: https://pub.dartlang.org/packages/flutter_webview_plugin
when i use PopupmenuButton with webviewscafold. the menus are not displayed on top of webview ... the webview kind of hides the menu

routes: {
        "/": (_) => new MyHomePage(title: "Flutter WebView Demo"),
        "/widget": (_) => new WebviewScaffold(
          url: selectedUrl,
          appBar: new AppBar(
            title: new Text("Test"),

            actions: <Widget>[
              new PopupMenuButton<Choice>( // overflow menu
                onSelected: _select,
                itemBuilder: (BuildContext context) {
                  return choices.skip(0).map((Choice choice) {
                    return new PopupMenuItem<Choice>(
                      value: choice,
                      child: new Icon(choice.icon),
                    );
                  }).toList();
                },
              ),

            ],
          ),

        )
      },

_Copied from original issue: dart-lang/pub-dartlang-dart#1095_

**Comment by GokulDharumar** [comment]
URL: https://pub.dartlang.org/packages/flutter_webview_plugin
when i use PopupmenuButton with webviewscafold. the menus are not displayed on top of webview ... the webview kind of hides the menu

routes: {
"/": () => new MyHomePage(title: "Flutter WebView Demo"),
"/widget": () => new WebviewScaffold(
url: selectedUrl,
appBar: new AppBar(
title: new Text("Test"),

        actions: <Widget>[
          new PopupMenuButton<Choice>( // overflow menu
            onSelected: _select,
            itemBuilder: (BuildContext context) {
              return choices.skip(0).map((Choice choice) {
                return new PopupMenuItem<Choice>(
                  value: choice,
                  child: new Icon(choice.icon),
                );
              }).toList();
            },
          ),


        ],
      ),

    )
  },

**Comment by lejard-h** [comment]
Since the webview is not a flutter widget, we draw Android webview or iOS webview on top of the flutter view, so a popup menu is not possible or any flutter widget on top of the webview is not possible

**Comment by GokulDharumar** [comment]
I see this plugin is able to do it. can  you please see if you can make
your plugin work too ..
https://pub.dartlang.org/packages/flutter_web_view


Thanks
Gokul Dharumar
