### ISSUE TITLE
Error starting on ios

### ISSUE THREAD

**Issue by Flocksserver** [dart-flitter/flutter_webview_plugin#45]
I tried to start the example on iOS. Following Error:

`flutter_app_test/ios/Runner/GeneratedPluginRegistrant.m:6:9: fatal error: 'flutter_webview_plugin/FlutterWebviewPlugin.h' file not found
    #import <flutter_webview_plugin/FlutterWebviewPlugin.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
Could not build the application for the simulator.
Error launching application on iPhone X.`

On Android it works fine.

**Comment by lejard-h** [comment]
Hello can you paste your `flutter doctor` here ?

**Comment by Flocksserver** [comment]
of course =)

`[✓] Flutter (Channel beta, v0.1.5, on Mac OS X 10.13.3 17D47, locale de-DE)
    • Flutter version 0.1.5 at /Users/xxx/flutter
    • Framework revision 3ea4d06340 (3 weeks ago), 2018-02-22 11:12:39 -0800
    • Engine revision ead227f118
    • Dart version 2.0.0-dev.28.0.flutter-0b4f01f759

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.2)
    • Android SDK at /Users/xxx/android-sdk/
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 26.0.2
    • ANDROID_HOME = /Users/xxx/android-sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[!] IntelliJ IDEA Ultimate Edition (version 2017.3.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] Connected devices (1 available)
    • iPhone X • 0FED7A86-1BF5-481E-AC77-5EB35543A53C • ios • iOS 11.2 (simulator)

`

**Comment by jparound30** [comment]
@Flocksserver maybe problem is related to `CocoaPods`.
if you created 'flutter_app_test' with iOS language: swift, your project's `Podfile` contained `use_frameworks!` line.
you may be able to solve the problem if comment it out.

**Comment by Flocksserver** [comment]
@jparound30 thanks - no effekt =/ BUT if i open the iOS project with xcode and compile it there... it works. but with flutter still the error. strange
