### ISSUE TITLE
Set AppBar in webview.launch(url)

### ISSUE THREAD

**Issue by JohannesKaufmann** [dart-flitter/flutter_webview_plugin#47]
You can't set the AppBar when using `launch(url)` and if you use the `WebviewScaffold` you can't access cookies, attach listeners, ...
Would it be possible to add the ability to specify the appbar when launching?
An API that is getting popular in the React community is the so called [“render prop”](https://reactjs.org/docs/render-props.html). Would that be possible in dart?
```dart
flutterWebviewPlugin.launch(
  url,
  appBar: (state) => new AppBar(...),
);

new WebviewScaffold(
  url: "https://www.google.com",
  appBar: (state) => new AppBar(
    title: new Text(state.url),
  ),
)
```
`state` could hold things like `url`, `host`, `isSecure` but also functions like `goBack()`, `close()`, `goTo(url)`. This would make it a lot easier to add functionality to the appbar buttons.

**Comment by lejard-h** [comment]
Are you trying to achieve something similar to this ? (https://github.com/dart-flitter/flutter_webview_plugin/issues/30)

The plugin does not allow to manage multiple webview and the FlutterWebviewPlugin instance is a singleton, 
so you can access to the current webview from anywhere and attach listener

**Comment by JohannesKaufmann** [comment]
I was not aware that you could access the properties on `flutterWebviewPlugin` if you use `WebviewScaffold`. Maybe make that clearer in the documentation for people that dont know what a `singleton` is:

> FlutterWebviewPlugin provide a singleton instance linked to one unique webview, so you can take control of the webview from anywhere in the app. That means that you can only have one webview open at a time and that you can use the `FlutterWebviewPlugin` instance to manipulate your `WebviewScaffold`.


I know that you can use the listeners to change the state which rerenders the widgets but the proposed api would make it alot easier to work with (but would be a breaking change). I should have put that into a seperate issue.
For example if you want to show the title and url of the page in the appbar (like twitter for example) you just need to use the variables instead of `ataching` listeners and remembering to `dispose` them again.
