### ISSUE TITLE
IOS - Fullscreen params should hide topBar

### ISSUE THREAD

**Issue by lejard-h** [dart-flitter/flutter_webview_plugin#5]
On IOS the fullscreen param should hide the topBar with the "Done" button, currently it seems to hide the statusBar instead.

Maybe we can have 2 differents params to handle both cases.

**Comment by toufikudemy** [comment]
So the problem is that since iOS doesn't have a back button, if we hide the navigation bar then there's no way to close the view. Android has the navigation bar with the dark background and the back arrow button. Do you want to have it match that instead?

**Comment by hlejard** [comment]
I have a usecase where the login page is a web view so the only solution for the user is to go out of the application, on both Android and iOS he should use the home button of the phone

**Comment by lejard-h** [comment]
I have a usecase where the login page is a web view so the only solution for the user is to go out of the application, on both Android and iOS he should use the home button of the phone

**Comment by chandmk** [comment]
Shouldn't there be top margin of 20 screen pixels in iOS in full screen mode?

**Comment by lejard-h** [comment]
why ? I am not an iOS dev or user. Do you have documentation about design spec on iOS ?

**Comment by chandmk** [comment]
I am talking about status bar height.  In the simulator, I am seeing the status bar overlay on the web site.

I am wondering if there should be an option to hide the status bar and when set to false, push the webview down the status bar.

http://ivomynttinen.com/blog/ios-design-guidelines

Search for status bar in that document.
