### ISSUE TITLE
Using SFSafariViewController on iOS

### ISSUE THREAD

**Issue by mikowm** [dart-flitter/flutter_webview_plugin#50]
Are there any plans to use `SFSafariViewController` instead of `UIWebView`? I've read [here](https://stackoverflow.com/questions/41990403/oauth-2-embedded-browsers-will-be-blocked) `SFSafariViewController` is necessary in apps using OAuth 2 authorization. I think iOS apps not using `SFSafariViewController` will be rejected in App Store.

I don't if there's something similar (a native web view showing the current url) in Android. I know I could show the url in the AppBar when using a `WebviewScaffold`, but it's not the same.

Thank you in advance for your response!

**Comment by lejard-h** [comment]
if it is mandatory we should do it yes. But I am not an iOS developer and I don't have much time right now. I accept PR if someone want to contribute, I can review the dart part

**Comment by lejard-h** [comment]
from what I read, we should use this class https://developer.apple.com/documentation/webkit/wkwebview

**Comment by samastur** [comment]
As a current Cordova user I can confirm that WKWebView is currently preferred and definitely by Apple accepted version of iOS WebView.

**Comment by ciceroduarte** [comment]
I sended a pr to use WKWebView instead of UIWebView 🙂 #54

**Comment by lejard-h** [comment]
landed on `0.1.5`

**Comment by mikowm** [comment]
Thank you! :)
