### ISSUE TITLE
Is it possible to serve a html file stored locally on the users phone?

### ISSUE THREAD

**Issue by twistedinferno** [dart-flitter/flutter_webview_plugin#52]
Serve html from the user's assets folder for instance?

Possibly related to this #23.

**Comment by zoechi** [comment]
Looks like #23 to me. Don't the suggestions work for you?

**Comment by twistedinferno** [comment]
I'm assessing Flutter and some plugins for the needs of a yet to be created app.  I will try it out today or tomorrow depending on where I get to and feedback :-)

**Comment by twistedinferno** [comment]
Yup, it works fine, just use the `new Uri.dataFromBytes`

```
    final flutterWebviewPlugin = new FlutterWebviewPlugin();
    flutterWebviewPlugin.launch(
        new Uri.dataFromBytes(myBytes, mimeType: 'text/html').toString(),
        rect: new Rect.fromLTWH(
            0.0, 0.0, MediaQuery.of(context).size.width, 300.0),
        userAgent: kAndroidUserAgent);

```
