### ISSUE TITLE
Inline Usage of WebView

### ISSUE THREAD

**Issue by p30arena** [dart-flitter/flutter_webview_plugin#55]
Hi!
How can I use the webview inline with other widgets?

**Comment by howardt12345** [comment]
I would like to know how to do this as well.

**Comment by lejard-h** [comment]
The plugin does not allow that kind of usage, the webview is not directly draw inside the widget tree.

The flutter team is working on it to be able to draw inline webview and also inline map
https://github.com/flutter/flutter/issues/730

**Comment by MisterJimson** [comment]
@hnvn track this work here flutter/flutter#730 as @lejard-h has noted.
