### ISSUE TITLE
Hello, I want to modify it myself, and then use it on my app, such as intercept URL and add request function, so I will push it to pub! OK? Thank you.

### ISSUE THREAD

**Issue by zhangruiyu** [dart-flitter/flutter_webview_plugin#67]
Hello, I want to modify it myself, and then use it on my app, such as intercept URL and add request function, so I will push it to pub! OK? Thank you.

**Comment by lejard-h** [comment]
you can use git path in pubspec

```
flutter_webview_plugin:
   git: <YOUR_REPO>
```

https://www.dartlang.org/tools/pub/dependencies
