### ISSUE TITLE
Does not support Chinese

### ISSUE THREAD

**Issue by 7449** [dart-flitter/flutter_webview_plugin#68]
English is normal, I got an error when I entered Chinese

english  

    new WebviewScaffold(
            url: new Uri.dataFromString(
                    '<html><body>hello</body></html>',
                    mimeType: 'text/html')
                .toString())

chinese

    new WebviewScaffold(
            url: new Uri.dataFromString(
                    '<html><body>你好</body></html>',
                    mimeType: 'text/html')
                .toString())

Hope to get a reply

thanks

**Comment by lejard-h** [comment]
did you try to run a custom server in your app, as describe here https://github.com/dart-flitter/flutter_webview_plugin/issues/23

**Comment by 7449** [comment]
my data is obtained from an api, this is related to the local server?

**Comment by jparound30** [comment]
this is not a bug.

should specify the `encoding` parameter.

```
import 'dart:convert';

new Uri.dataFromString(
                  '<html><body>你好</body></html>',
                  mimeType: 'text/html',
                  encoding: utf8)
                  .toString())
```

**Comment by 7449** [comment]
thanks,this is not a bug,It to be my problem
