### ISSUE TITLE
Getting data from the webview

### ISSUE THREAD

**Issue by bramvbilsen** [dart-flitter/flutter_webview_plugin#7]
Is it possible to for example signing in with facebook and getting back the token and id?

**Comment by toufikzitouni** [comment]
Yep! I followed the steps on this blog and it worked successfully for me  https://medium.com/@segaud.kevin/facebook-oauth-login-flow-with-flutter-9adb717c9f2e

**Comment by lejard-h** [comment]
The article from Medium is a good start and we have an implementation here https://github.com/dart-flitter/flitter/blob/master/lib/services/flutter_gitter_auth.dart#L40
