### ISSUE TITLE
The example code throws an error on both android and IOS

### ISSUE THREAD

**Issue by agozie** [dart-flitter/flutter_webview_plugin#73]
I get this exception when I click any of the open buttons:

`Exception has occurred.
type '_InternalLinkedHashMap<dynamic, dynamic>' is not a subtype of type 'Map<String, dynamic>' where
  _InternalLinkedHashMap is from dart:collection
  Map is from dart:core
  String is from dart:core`

I'm on flutter 0.3.7-pre.9 with vs code as editor.

**Comment by lejard-h** [comment]
should be fix in `0.1.6`
