### ISSUE TITLE
Receiving Cookies in WebView

### ISSUE THREAD

**Issue by r-wittmann** [dart-flitter/flutter_webview_plugin#9]
I was wondering, if it is possible to get data from cookies, set in the web view, to the flutter application. My use case is a custom auth mechanism which works by authentication with google on server side and sending a cookie with the client credentials in a cookie to the frontend (in this case my flutter app). Is this possible with this plugin? 

I saw both #7 and #8 and am not sure about this approach because of the cookie instead of a redirect url and query parameters.

**Comment by lejard-h** [comment]
Not possible for now, but it is possible to get cookies from webView on Android so we could manage share cookies from webview with the flutter side.

On iOS I don't know yet.

**Comment by chances** [comment]
@lejard-h For iOS, It seem's an app's cookies are stored in their own cookie jar:

> ```NSHTTPCookie *cookie;
> NSHTTPCookieStorage *cookieJar = [NSHTTPCookieStorage sharedHTTPCookieStorage];
> for (cookie in [cookieJar cookies]) {
>    NSLog(@"%@", cookie);
> }
(From [StackOverflow](https://stackoverflow.com/questions/771498/where-are-an-uiwebviews-cookies-stored))

Not sure how outdated/accurate that answer is, though.

**Comment by marwan-at-work** [comment]
this would be very helpful

**Comment by lejard-h** [comment]
`Future<Map<String, dynamic>> getCookies()` for the next release `0.0.10`, 
also via eval function
`final cookiesString = await evalJavascript("document.cookie");`

**Comment by marwan-at-work** [comment]
@lejard-h is there a roadmap for the release i can follow up with? tks!

**Comment by lucaslcode** [comment]
@marwan-at-work I'm interested in this too, looks like it's already been released in 0.0.10 (check the code)

**Comment by marwan-at-work** [comment]
@lucaslcode i don't see it in pub yet https://pub.dartlang.org/packages/flutter_webview_plugin#-versions-tab-

**Comment by lejard-h** [comment]
Not on pub yet, the release is blocked by #22 and #21, but if you are not concern by those issues, you can use the package directly from github and I am open to any contribution especially for iOS.

**Comment by bvedam** [comment]
Any update on ability to set cookies in webview for both Android and iOS? If not, is it the plan in the near term? Appreciate your response. Thx.

**Comment by BRO3886** [comment]
Any update?
