### ISSUE TITLE
Can't open specific links on iOS

### ISSUE THREAD

**Issue by wardweistra** [dart-flitter/flutter_webview_plugin#94]
Dear developers,

I love your webview plugin for the Oauth flow in my app. It works on Android, however I am having trouble on iOS, both on the emulator and real device. The following links result in a white webview:
- http://postgres-test.transmartfoundation.org/transmart/oauth/authorize?response_type=code&client_id=api-client&client_secret=api-client&redirect_uri=http%3A%2F%2Fpostgres-test.transmartfoundation.org%2Ftransmart%2Foauth%2Fverify (the Oauth link I am looking to open)
- http://thehyve.nl (My company's website, but on http instead of https, which normally redirects)

Both do work on Android. Also the http**s**://thehyve.nl does load, leading me to believe it might be redirect related.
You should be able to reproduce this by just taking the example application in this repository and putting the above links in there.

Would really appreciate your suggestions!

Best regards,
Ward

**Comment by wardweistra** [comment]
OK, I now understand it could only load websites on my domain and https on iOS by default. Since I need arbitrary domains, I had to add the following to `ios/Runner/Info.plist`:

```
<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
		<key>NSAllowsArbitraryLoadsInWebContent</key>
		<true/>
	</dict>
```

`NSAllowsArbitraryLoadsInWebContent ` is for iOS 10+ and `NSAllowsArbitraryLoads ` for iOS 9.

https://stackoverflow.com/questions/41557155/wkwebview-how-to-display-links-to-http-pages

**Comment by brunovsiqueira** [comment]
@wardweistra I added this key but it is still not working. The callbacks of FlutterWebViewPlugin are never called, and I am using onUrlChanged.listen. Can you help me please?

**Comment by wardweistra** [comment]
@brunovsiqueira I'm afraid not. Above is all I know, which worker at that point in time with those iOS versions. Perhaps a solution mentioned in https://github.com/fluttercommunity/flutter_webview_plugin/issues/229 or else open a new issue.
